/** @typedef {import('../attribute').Attribute} Attribute */
const { AttributeType } = require('../attribute');
const { LanguageMeta } = require("./language");

class Python extends LanguageMeta {
  getType(attribute, collections, flavor = 'typeddict') {
    let baseType = "";
    
    // Determine base type
    switch (attribute.type) {
      case AttributeType.STRING:
      case AttributeType.EMAIL:
      case AttributeType.DATETIME:
      case AttributeType.IP:
      case AttributeType.URL:
        if (attribute.format === AttributeType.ENUM) {
          baseType = LanguageMeta.toPascalCase(attribute.key);
        } else {
          baseType = "str";
        }
        break;
      case AttributeType.INTEGER:
        baseType = "int";
        break;
      case AttributeType.FLOAT:
        baseType = "float";
        break;
      case AttributeType.BOOLEAN:
        baseType = "bool";
        break;
      case AttributeType.RELATIONSHIP:
        const relatedCollection = collections.find(c => c.$id === attribute.relatedCollection);
        if (!relatedCollection) {
          throw new Error(`Related collection with ID '${attribute.relatedCollection}' not found.`);
        }
        baseType = LanguageMeta.toPascalCase(relatedCollection.name);
        if ((attribute.relationType === 'oneToMany' && attribute.side === 'parent') || 
            (attribute.relationType === 'manyToOne' && attribute.side === 'child') || 
            attribute.relationType === 'manyToMany') {
          baseType = `list[${baseType}]`;
        }
        break;
      default:
        throw new Error(`Unknown attribute type: ${attribute.type}`);
    }
    
    // Handle array types based on flavor
    if (attribute.array) {
      if (flavor === 'typeddict' || flavor === 'pydantic310') {
        baseType = `list[${baseType}]`;
      } else {
        baseType = `List[${baseType}]`;
      }
    }
    
    // Handle optional types based on flavor
    if (!attribute.required) {
      if (flavor === 'typeddict') {
        // TypedDict uses union syntax
        baseType = `${baseType} | None`;
      } else if (flavor === 'pydantic310') {
        // Python 3.10+ built-in typing
        baseType = `${baseType} | None`;
      } else {
        // Pydantic v2 with typing imports
        baseType = `Optional[${baseType}]`;
      }
    }
    
    return baseType;
  }

  getFieldDefinition(attribute, collections) {
    const fieldArgs = [];
    
    // Handle required vs optional with default
    if (attribute.required) {
      fieldArgs.push("...");
    } else if (attribute.default !== null && attribute.default !== undefined) {
      // Use the actual default value with proper Python formatting
      if (typeof attribute.default === 'string') {
        fieldArgs.push(`"${attribute.default}"`);
      } else if (typeof attribute.default === 'boolean') {
        fieldArgs.push(attribute.default ? "True" : "False");
      } else {
        fieldArgs.push(String(attribute.default));
      }
    } else {
      fieldArgs.push("None");
    }
    
    // Add constraints
    const constraints = [];
    
    // Handle size constraint for strings
    if (attribute.size && (attribute.type === AttributeType.STRING || 
                          attribute.type === AttributeType.EMAIL ||
                          attribute.type === AttributeType.URL)) {
      constraints.push(`max_length=${attribute.size}`);
    }
    
    // Add all constraints
    if (constraints.length > 0) {
      fieldArgs.push(...constraints);
    }
    
    return `Field(${fieldArgs.join(', ')})`;
  }

  isSingleFile() {
    return true;
  }

  getTemplate() {
    return `<% if (flavor === 'typeddict') { -%>
"""
Auto-generated types for Appwrite collections.
Generated by the Appwrite CLI: appwrite ${process.argv.slice(2).join(' ')}
"""

from typing import TypedDict, Literal
from datetime import datetime

<% for (const collection of collections) { -%>
<% for (const attribute of collection.attributes) { -%>
<% if (attribute.format === 'enum') { -%>
<%- toPascalCase(attribute.key) %> = Literal[<%- attribute.elements.map(el => '"' + el + '"').join(', ') %>]

<% } -%>
<% } -%>
<% } -%>
<% for (const [index, collection] of Object.entries(collections)) { -%>
class <%- toPascalCase(collection.name) %>(TypedDict):
    """<%- collection.name %> document type."""
    # System fields  
    id: str  # $id
    created_at: datetime  # $createdAt
    updated_at: datetime  # $updatedAt
    permissions: list[str]  # $permissions
    
    # Collection fields
<% for (const attribute of collection.attributes) { -%>
    <%- strict ? toSnakeCase(attribute.key) : attribute.key %>: <%- getType(attribute, collections, flavor) %>
<% } -%>
<% if (index < collections.length - 1) { %>

<% } -%>
<% } -%>
<% } else if (flavor === 'pydantic310') { -%>
"""
Auto-generated types for Appwrite collections.
Generated by the Appwrite CLI: appwrite ${process.argv.slice(2).join(' ')}
"""

from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime

<% for (const collection of collections) { -%>
<% for (const attribute of collection.attributes) { -%>
<% if (attribute.format === 'enum') { -%>
from typing import Literal
<%- toPascalCase(attribute.key) %> = Literal[<%- attribute.elements.map(el => '"' + el + '"').join(', ') %>]

<% } -%>
<% } -%>
<% } -%>

class AppwriteDocument(BaseModel):
    """Base class for all Appwrite documents."""
    model_config = ConfigDict(populate_by_name=True)
    
    id: str = Field(..., alias="$id")
    created_at: datetime = Field(..., alias="$createdAt")
    updated_at: datetime = Field(..., alias="$updatedAt")
    permissions: list[str] = Field(..., alias="$permissions")

<% for (const [index, collection] of Object.entries(collections)) { -%>
class <%- toPascalCase(collection.name) %>(AppwriteDocument):
    """<%- collection.name %> document type."""
<% for (const attribute of collection.attributes) { -%>
    <%- strict ? toSnakeCase(attribute.key) : attribute.key %>: <%- getType(attribute, collections, flavor) %> = <%- getFieldDefinition(attribute, collections) %>
<% } -%>
<% if (index < collections.length - 1) { %>

<% } -%>
<% } -%>
<% } else { // default pydantic -%>
"""
Auto-generated types for Appwrite collections.
Generated by the Appwrite CLI: appwrite ${process.argv.slice(2).join(' ')}
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Literal
from datetime import datetime

<% for (const collection of collections) { -%>
<% for (const attribute of collection.attributes) { -%>
<% if (attribute.format === 'enum') { -%>
<%- toPascalCase(attribute.key) %> = Literal[<%- attribute.elements.map(el => '"' + el + '"').join(', ') %>]

<% } -%>
<% } -%>
<% } -%>

class AppwriteDocument(BaseModel):
    """Base class for all Appwrite documents."""
    model_config = ConfigDict(populate_by_name=True)
    
    id: str = Field(..., alias="$id")
    created_at: datetime = Field(..., alias="$createdAt")
    updated_at: datetime = Field(..., alias="$updatedAt")
    permissions: List[str] = Field(..., alias="$permissions")

<% for (const [index, collection] of Object.entries(collections)) { -%>
class <%- toPascalCase(collection.name) %>(AppwriteDocument):
    """<%- collection.name %> document type."""
<% for (const attribute of collection.attributes) { -%>
    <%- strict ? toSnakeCase(attribute.key) : attribute.key %>: <%- getType(attribute, collections, flavor) %> = <%- getFieldDefinition(attribute, collections) %>
<% } -%>
<% if (index < collections.length - 1) { %>

<% } -%>
<% } -%>
<% } -%>`;
  }

  getFileName(_) {
    return "appwrite_types.py";
  }
}

module.exports = { Python };